# Generated by Django 3.1 on 2022-01-15 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='placing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_mainimg', models.ImageField(upload_to='dynamic_pic')),
                ('place_img1', models.ImageField(blank=True, upload_to='dynamic_pic')),
                ('place_img2', models.ImageField(blank=True, upload_to='dynamic_pic')),
                ('place_img3', models.ImageField(blank=True, upload_to='dynamic_pic')),
                ('place_img4', models.ImageField(blank=True, upload_to='dynamic_pic')),
                ('place_city', models.CharField(max_length=100)),
                ('place_state', models.CharField(choices=[('AND', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('ARP', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BI', 'Bihar'), ('CH', 'Chandigarh'), ('CHH', 'Chhattisgarh'), ('DD', 'Dadra & Nagar Haveli and Daman & Diu'), ('DL', 'Delhi'), ('GO', 'Goa'), ('GU', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KR', 'Karnataka'), ('KRL', 'Kerala'), ('LD', 'Lakshadweep'), ('LH', 'Ladakh'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('MG', 'Meghalaya'), ('MZ', 'Mizoram'), ('NG', 'Nagaland'), ('OD', 'Odisha'), ('PJ', 'Punjab'), ('PD', 'Puducherry'), ('RS', 'Rajasthan'), ('SI', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=100)),
                ('place_smdesc', models.TextField(max_length=180)),
                ('place_desc', models.TextField()),
                ('cs_available', models.BooleanField(default=False)),
                ('cs_img', models.ImageField(blank=True, upload_to='dynamic_pic')),
                ('cs_name', models.CharField(blank=True, max_length=100)),
                ('cs_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100)),
                ('cs_number', models.IntegerField(blank=True, max_length=10)),
                ('cs_address', models.CharField(blank=True, max_length=100)),
                ('cs_proff', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
