# Generated by Django 3.1 on 2022-01-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placing',
            name='cs_number',
            field=models.IntegerField(blank=True),
        ),
    ]
