# Generated by Django 3.1 on 2022-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20220116_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placing',
            name='cs_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
