# Generated by Django 3.1 on 2022-03-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='analy',
            field=models.CharField(default='Neutral', max_length=100),
        ),
    ]
