# Generated by Django 3.1 on 2021-11-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cimg', models.ImageField(upload_to='dynamic_pic')),
                ('cdesc', models.TextField()),
            ],
        ),
    ]
