# Generated by Django 3.1 on 2021-11-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmain', '0002_topplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='topplace',
            name='place_city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topplace',
            name='place_state',
            field=models.CharField(choices=[('AND', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('ARP', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BI', 'Bihar'), ('CH', 'Chandigarh'), ('CHH', 'Chhattisgarh'), ('DD', 'Dadra & Nagar Haveli and Daman & Diu'), ('DL', 'Delhi'), ('GO', 'Goa'), ('GU', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KR', 'Karnataka'), ('KRL', 'Kerala'), ('LD', 'Lakshadweep'), ('LH', 'Ladakh'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('MG', 'Meghalaya'), ('MZ', 'Mizoram'), ('NG', 'Nagaland'), ('OD', 'Odisha'), ('PJ', 'Punjab'), ('PD', 'Puducherry'), ('RS', 'Rajasthan'), ('SI', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topplace',
            name='place_desc',
            field=models.TextField(max_length=65),
        ),
    ]
