# Generated by Django 3.1 on 2021-11-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmain', '0003_auto_20211110_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topplace',
            name='place_desc',
            field=models.TextField(max_length=120),
        ),
    ]
