# Generated by Django 3.1 on 2021-11-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmain', '0004_auto_20211110_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopPlace',
        ),
    ]
